# Generated by Django 4.2.7 on 2025-11-17 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note_type', models.CharField(choices=[('soap', 'SOAP Note'), ('progress', 'Progress Note'), ('consultation', 'Consultation Note'), ('admission', 'Admission Note'), ('discharge', 'Discharge Summary'), ('procedure', 'Procedure Note'), ('operative', 'Operative Note'), ('followup', 'Follow-up Note')], db_index=True, max_length=20)),
                ('note_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('chief_complaint', models.TextField(help_text="Patient's main reason for visit")),
                ('content', models.TextField(help_text='Main clinical note content')),
                ('diagnosis', models.TextField(blank=True, help_text='Primary and differential diagnoses')),
                ('treatment_plan', models.TextField(blank=True, help_text='Treatment and management plan')),
                ('follow_up_instructions', models.TextField(blank=True, help_text='Instructions for patient follow-up')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attached file URLs or references')),
            ],
            options={
                'verbose_name': 'Clinical Note',
                'verbose_name_plural': 'Clinical Notes',
                'ordering': ['-note_date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNoteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('note_type', models.CharField(choices=[('soap', 'SOAP Note'), ('progress', 'Progress Note'), ('consultation', 'Consultation Note'), ('admission', 'Admission Note'), ('discharge', 'Discharge Summary'), ('procedure', 'Procedure Note'), ('operative', 'Operative Note'), ('followup', 'Follow-up Note')], db_index=True, max_length=20)),
                ('template_content', models.TextField(help_text='Template with placeholders like {{patient_name}}, {{date}}, etc.')),
                ('is_system_template', models.BooleanField(default=False, help_text='Whether this is a system-wide template')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Clinical Note Template',
                'verbose_name_plural': 'Clinical Note Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SOAPNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subjective', models.TextField(help_text="Patient's subjective description of their condition")),
                ('objective', models.TextField(help_text='Objective findings: vital signs, physical exam, lab results')),
                ('assessment', models.TextField(help_text='Clinical assessment and diagnosis')),
                ('plan', models.TextField(help_text='Treatment plan and next steps')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Temperature in Fahrenheit', max_digits=4, null=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='BPM', null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='Breaths per minute', null=True)),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, help_text='SpO2 percentage', null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in pounds', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in inches', max_digits=5, null=True)),
                ('clinical_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soap_details', to='clinical_notes.clinicalnote')),
            ],
            options={
                'verbose_name': 'SOAP Note',
                'verbose_name_plural': 'SOAP Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.TextField(help_text="Patient's current condition and status")),
                ('progress_since_last_visit', models.TextField(blank=True, help_text='Changes since last visit')),
                ('symptoms_update', models.TextField(blank=True, help_text='Update on symptoms')),
                ('medications_review', models.TextField(blank=True, help_text='Review of current medications and effectiveness')),
                ('treatment_effectiveness', models.TextField(blank=True, help_text='How well is the treatment working')),
                ('plan_modifications', models.TextField(blank=True, help_text='Any changes to the treatment plan')),
                ('next_steps', models.TextField(blank=True, help_text='Next steps in care')),
                ('treatment_goals', models.TextField(blank=True, help_text='Treatment goals and milestones')),
                ('goals_achieved', models.TextField(blank=True, help_text='Goals that have been achieved')),
                ('clinical_note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_details', to='clinical_notes.clinicalnote')),
            ],
            options={
                'verbose_name': 'Progress Note',
                'verbose_name_plural': 'Progress Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
