# Generated by Django 4.2.7 on 2025-11-17 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_notes', '0001_initial'),
        ('doctors', '0001_initial'),
        ('appointments', '0002_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnotetemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_notes', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['patient', 'note_date'], name='clinical_no_patient_604bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['doctor', 'note_date'], name='clinical_no_doctor__46db14_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['note_type', 'note_date'], name='clinical_no_note_ty_0de774_idx'),
        ),
    ]
