# Google Cloud Build configuration for Clinic CRM Backend
# Triggers automatic builds and deployments to Cloud Run

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: clinic-backend
  _CLOUD_SQL_INSTANCE: clinic-sql

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    dir: 'backend'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'DJANGO_SETTINGS_MODULE=config.settings.production'
      - '--set-env-vars'
      - 'DB_NAME=clinic'
      - '--set-env-vars'
      - 'DB_USER=postgres'
      - '--set-env-vars'
      - 'CLOUD_SQL_CONNECTION_NAME=$PROJECT_ID:${_REGION}:${_CLOUD_SQL_INSTANCE}'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:${_REGION}:${_CLOUD_SQL_INSTANCE}'
      - '--set-secrets'
      - 'DB_PASSWORD=clinic-db-password:latest'
      - '--set-secrets'
      - 'SECRET_KEY=django-secret-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
