# Generated by Django 4.2.7 on 2025-11-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_walk_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_order',
            field=models.IntegerField(default=0, help_text='Manual override for queue position'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='urgency',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], db_index=True, default='routine', max_length=20),
        ),
    ]
