# Generated by Django 4.2.7 on 2025-12-03 12:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0002_initial"),
        (
            "appointments",
            "0003_appointment_is_walk_in_appointment_queue_order_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of the week",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Schedule start time (e.g., 08:00)"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="Schedule end time (e.g., 17:00)"),
                ),
                (
                    "break_start",
                    models.TimeField(
                        blank=True, help_text="Lunch break start time", null=True
                    ),
                ),
                (
                    "break_end",
                    models.TimeField(
                        blank=True, help_text="Lunch break end time", null=True
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether doctor is available on this day",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="Doctor this schedule belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Schedule",
                "verbose_name_plural": "Doctor Schedules",
                "ordering": ["day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "day_of_week"],
                        name="appointment_doctor__c1bf72_idx",
                    ),
                    models.Index(
                        fields=["is_available"], name="appointment_is_avai_691c32_idx"
                    ),
                ],
                "unique_together": {("doctor", "day_of_week")},
            },
        ),
    ]
