# Generated by Django 4.2.7 on 2025-11-18 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_email", models.EmailField(db_index=True, max_length=254)),
                ("user_role", models.CharField(db_index=True, max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("READ", "Read"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("LIST", "List"),
                            ("EXPORT", "Export"),
                            ("PRINT", "Print"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of resource accessed (e.g., Patient, Appointment)",
                        max_length=50,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of specific resource (null for LIST actions)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="Human-readable description of the action"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("query_params", models.TextField(blank=True)),
                ("was_successful", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="core_auditl_user_id_413764_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="core_auditl_action_29a2bf_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "created_at"],
                        name="core_auditl_resourc_c208a6_idx",
                    ),
                    models.Index(
                        fields=["user_email", "created_at"],
                        name="core_auditl_user_em_7b953b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="core_auditl_created_dc23ea_idx"
                    ),
                ],
            },
        ),
    ]
