# Generated by Django 4.2.7 on 2025-11-26 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="state",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="patient",
            name="postal_code",
            field=models.CharField(blank=True, help_text="Postal Code", max_length=10),
        ),
        migrations.AddField(
            model_name="patient",
            name="province",
            field=models.CharField(blank=True, help_text="Province", max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address_line1",
            field=models.CharField(
                blank=True, help_text="Street address", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address_line2",
            field=models.CharField(
                blank=True, help_text="Barangay/Village", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="city",
            field=models.CharField(
                blank=True, help_text="Municipality or City", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be a valid Philippine number (e.g., +63912345678 or 09123456789)",
                        regex="^\\+?63\\d{9,10}$|^\\+?639\\d{8,9}$|^09\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be a valid Philippine number (e.g., +63912345678 or 09123456789)",
                        regex="^\\+?63\\d{9,10}$|^\\+?639\\d{8,9}$|^09\\d{9}$",
                    )
                ],
            ),
        ),
    ]
