# Generated by Django 4.2.7 on 2025-11-26 10:20

import apps.patients.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_update_patient_address_for_philippines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="medical_record_number",
            field=models.CharField(
                db_index=True,
                default=apps.patients.models.generate_medical_record_number,
                help_text="Unique medical record number (MRN) - Auto-generated",
                max_length=50,
                unique=True,
            ),
        ),
    ]
