# Generated by Django 4.2.7 on 2025-11-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_alter_patient_medical_record_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="General notes about the patient (administrative, non-clinical)",
            ),
        ),
    ]
