# Generated by Django 4.2.7 on 2025-11-17 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('annual_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Annual budget in USD', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee_id', models.CharField(db_index=True, help_text='Unique employee ID number', max_length=50, unique=True)),
                ('position', models.CharField(help_text='Job title', max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('intern', 'Intern')], default='full_time', max_length=20)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('retired', 'Retired')], db_index=True, default='active', max_length=20)),
                ('hire_date', models.DateField(db_index=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('last_promotion_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Annual salary or hourly rate', max_digits=12, null=True)),
                ('pay_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('annually', 'Annually')], default='biweekly', max_length=20)),
                ('benefits_enrolled', models.JSONField(blank=True, default=list, help_text='List of benefits employee is enrolled in')),
                ('work_schedule', models.JSONField(blank=True, default=dict, help_text='Weekly work schedule')),
                ('pto_balance', models.DecimalField(decimal_places=2, default=0, help_text='Paid time off balance in days', max_digits=6)),
                ('performance_rating', models.CharField(blank=True, help_text='Latest performance rating', max_length=50)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='employee_documents/')),
                ('contract', models.FileField(blank=True, null=True, upload_to='employee_documents/')),
                ('notes', models.TextField(blank=True, help_text='Internal HR notes')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePerformanceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_type', models.CharField(choices=[('annual', 'Annual Review'), ('probation', 'Probation Review'), ('mid_year', 'Mid-Year Review'), ('project', 'Project Review'), ('other', 'Other')], max_length=20)),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('review_date', models.DateField(db_index=True)),
                ('overall_rating', models.DecimalField(decimal_places=1, help_text='Overall rating (1-5 scale)', max_digits=3)),
                ('technical_skills_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('communication_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('teamwork_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('leadership_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('areas_for_improvement', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True, help_text='Goals for next review period')),
                ('comments', models.TextField(blank=True)),
                ('employee_acknowledged', models.BooleanField(default=False)),
                ('employee_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('review_document', models.FileField(blank=True, null=True, upload_to='performance_reviews/')),
            ],
            options={
                'verbose_name': 'Performance Review',
                'verbose_name_plural': 'Performance Reviews',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pto_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('personal', 'Personal Day'), ('bereavement', 'Bereavement'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('days_requested', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for time off')),
                ('denial_reason', models.TextField(blank=True, help_text='Reason for denial if denied')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Employee Time Off',
                'verbose_name_plural': 'Employee Time Off Requests',
                'ordering': ['-start_date'],
            },
        ),
    ]
