# Generated by Django 4.2.7 on 2025-11-17 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetimeoff',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_off', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetimeoff',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_requests', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeeperformancereview',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeeperformancereview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='employeetimeoff',
            index=models.Index(fields=['employee', 'start_date'], name='employees_e_employe_814e55_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetimeoff',
            index=models.Index(fields=['status', 'start_date'], name='employees_e_status_45d21e_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeperformancereview',
            index=models.Index(fields=['employee', 'review_date'], name='employees_e_employe_6145b9_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeperformancereview',
            index=models.Index(fields=['review_type', 'review_date'], name='employees_e_review__f85263_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'employment_status'], name='employees_e_departm_ac5287_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['manager'], name='employees_e_manager_278e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['hire_date'], name='employees_e_hire_da_c2151e_idx'),
        ),
    ]
