# Generated by Django 4.2.7 on 2025-11-17 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ndc_code', models.CharField(blank=True, help_text='National Drug Code', max_length=20, unique=True)),
                ('brand_name', models.CharField(db_index=True, max_length=200)),
                ('generic_name', models.CharField(db_index=True, max_length=200)),
                ('drug_class', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('analgesic', 'Analgesic'), ('antihypertensive', 'Antihypertensive'), ('antidiabetic', 'Antidiabetic'), ('anticoagulant', 'Anticoagulant'), ('antidepressant', 'Antidepressant'), ('antipsychotic', 'Antipsychotic'), ('antihistamine', 'Antihistamine'), ('bronchodilator', 'Bronchodilator'), ('corticosteroid', 'Corticosteroid'), ('vitamin', 'Vitamin/Supplement'), ('other', 'Other')], db_index=True, max_length=50)),
                ('controlled_substance_schedule', models.CharField(blank=True, help_text='DEA schedule (I, II, III, IV, V) if controlled substance', max_length=10)),
                ('strength', models.CharField(help_text='e.g., 500mg, 10mg/5ml', max_length=100)),
                ('dosage_form', models.CharField(help_text='e.g., tablet, capsule, liquid, injection', max_length=100)),
                ('typical_dosage', models.CharField(blank=True, help_text='Typical dosage instructions', max_length=200)),
                ('indications', models.TextField(blank=True, help_text="What it's used for")),
                ('contraindications', models.TextField(blank=True, help_text='When NOT to use')),
                ('side_effects', models.TextField(blank=True, help_text='Common side effects')),
                ('interactions', models.TextField(blank=True, help_text='Drug interactions')),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_formulary', models.BooleanField(default=True, help_text="Whether this medication is on the clinic's formulary")),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'ordering': ['generic_name', 'brand_name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('prescription_number', models.CharField(db_index=True, help_text='Unique prescription number', max_length=50, unique=True)),
                ('prescribed_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('dosage', models.CharField(help_text='e.g., 500mg', max_length=200)),
                ('frequency', models.CharField(help_text='e.g., twice daily, every 6 hours', max_length=200)),
                ('route', models.CharField(default='oral', help_text='e.g., oral, topical, injection', max_length=50)),
                ('duration', models.CharField(help_text='e.g., 10 days, 3 months', max_length=100)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units (tablets, ml, etc.)', validators=[django.core.validators.MinValueValidator(1)])),
                ('refills_allowed', models.PositiveIntegerField(default=0, help_text='Number of refills allowed')),
                ('refills_remaining', models.PositiveIntegerField(default=0, help_text='Number of refills remaining')),
                ('instructions', models.TextField(help_text='Full instructions for patient (e.g., take with food)')),
                ('indication', models.TextField(blank=True, help_text='Reason for prescription')),
                ('pharmacy_name', models.CharField(blank=True, max_length=200)),
                ('pharmacy_phone', models.CharField(blank=True, max_length=17)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('on_hold', 'On Hold')], db_index=True, default='active', max_length=20)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('last_filled_date', models.DateField(blank=True, null=True)),
                ('dea_number_used', models.CharField(blank=True, help_text='DEA number if controlled substance', max_length=9)),
                ('electronically_sent', models.BooleanField(default=False)),
                ('sent_to_pharmacy_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='doctors.doctor')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='prescriptions.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescribed_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionRefill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('requested_by_patient', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('denied', 'Denied'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('filled_date', models.DateField(blank=True, null=True)),
                ('pharmacy_name', models.CharField(blank=True, max_length=200)),
                ('quantity_filled', models.PositiveIntegerField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refills', to='doctors.doctor')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_requests', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Refill',
                'verbose_name_plural': 'Prescription Refills',
                'ordering': ['-requested_date'],
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['generic_name'], name='prescriptio_generic_f67768_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['brand_name'], name='prescriptio_brand_n_3231be_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['drug_class', 'is_active'], name='prescriptio_drug_cl_497e39_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionrefill',
            index=models.Index(fields=['prescription', 'status'], name='prescriptio_prescri_595957_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionrefill',
            index=models.Index(fields=['status', 'requested_date'], name='prescriptio_status_9344d4_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'prescribed_date'], name='prescriptio_patient_473a79_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['doctor', 'prescribed_date'], name='prescriptio_doctor__bbf2e9_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['medication', 'status'], name='prescriptio_medicat_53afa8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status', 'expiration_date'], name='prescriptio_status_a81325_idx'),
        ),
    ]
