# Generated by Django 4.2.7 on 2025-12-03 08:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PSGCRegion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "psgc_id",
                    models.CharField(
                        db_index=True, help_text="PSGC code", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "correspondence_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="locations_p_name_35f49e_idx"),
                    models.Index(
                        fields=["psgc_id"], name="locations_p_psgc_id_b5a73a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PSGCProvince",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "psgc_id",
                    models.CharField(
                        db_index=True, help_text="PSGC code", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "correspondence_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provinces",
                        to="locations.psgcregion",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PSGCMunicipality",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "psgc_id",
                    models.CharField(
                        db_index=True, help_text="PSGC code", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "correspondence_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "is_city",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a city, False if municipality",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="municipalities",
                        to="locations.psgcprovince",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PSGCBarangay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "psgc_id",
                    models.CharField(
                        db_index=True, help_text="PSGC code", max_length=20, unique=True
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "correspondence_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "municipality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barangays",
                        to="locations.psgcmunicipality",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="psgcprovince",
            index=models.Index(fields=["name"], name="locations_p_name_562eff_idx"),
        ),
        migrations.AddIndex(
            model_name="psgcprovince",
            index=models.Index(
                fields=["psgc_id"], name="locations_p_psgc_id_bb2f77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="psgcprovince",
            index=models.Index(
                fields=["region"], name="locations_p_region__ec4843_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="psgcmunicipality",
            index=models.Index(fields=["name"], name="locations_p_name_bc5ecb_idx"),
        ),
        migrations.AddIndex(
            model_name="psgcmunicipality",
            index=models.Index(
                fields=["psgc_id"], name="locations_p_psgc_id_2ed6f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="psgcmunicipality",
            index=models.Index(
                fields=["province"], name="locations_p_provinc_539564_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="psgcbarangay",
            index=models.Index(fields=["name"], name="locations_p_name_e5d6ce_idx"),
        ),
        migrations.AddIndex(
            model_name="psgcbarangay",
            index=models.Index(
                fields=["psgc_id"], name="locations_p_psgc_id_1ad581_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="psgcbarangay",
            index=models.Index(
                fields=["municipality"], name="locations_p_municip_c6e827_idx"
            ),
        ),
    ]
