# Generated by Django 4.2.7 on 2025-11-17 11:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('license_number', models.CharField(db_index=True, help_text='State medical license number', max_length=50, unique=True)),
                ('npi_number', models.CharField(blank=True, help_text='National Provider Identifier (10 digits)', max_length=10, unique=True)),
                ('dea_number', models.CharField(blank=True, help_text='DEA number for prescribing controlled substances', max_length=9)),
                ('board_certified', models.BooleanField(default=False)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Standard consultation fee in USD', max_digits=10, null=True)),
                ('is_accepting_patients', models.BooleanField(default=True, help_text='Whether the doctor is currently accepting new patients')),
                ('bio', models.TextField(blank=True, help_text='Professional biography')),
                ('education', models.TextField(blank=True, help_text='Educational background')),
                ('languages', models.CharField(blank=True, help_text='Languages spoken (comma-separated)', max_length=200)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('medical_code', models.CharField(blank=True, help_text='Medical specialty code (e.g., NUCC taxonomy code)', max_length=20)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_type', models.CharField(choices=[('license', 'Medical License'), ('board_cert', 'Board Certification'), ('fellowship', 'Fellowship'), ('certification', 'Certification'), ('other', 'Other')], max_length=20)),
                ('credential_name', models.CharField(max_length=200)),
                ('issuing_organization', models.CharField(max_length=200)),
                ('credential_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, help_text='Scanned copy of the credential', null=True, upload_to='doctor_credentials/')),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Credential',
                'verbose_name_plural': 'Doctor Credentials',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently active')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedules', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Availability',
                'verbose_name_plural': 'Doctor Availabilities',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='doctors.specialization'),
        ),
    ]
