# Generated by Django 4.2.7 on 2025-11-17 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='doctorcredential',
            index=models.Index(fields=['doctor', 'credential_type'], name='doctors_doc_doctor__dbd7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorcredential',
            index=models.Index(fields=['expiry_date'], name='doctors_doc_expiry__d38585_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoravailability',
            index=models.Index(fields=['doctor', 'day_of_week', 'is_active'], name='doctors_doc_doctor__909fb7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'day_of_week', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['license_number'], name='doctors_doc_license_3eaac3_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['npi_number'], name='doctors_doc_npi_num_381c62_idx'),
        ),
    ]
