# Generated by Django 4.2.7 on 2025-11-17 11:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_name', models.CharField(db_index=True, max_length=200)),
                ('plan_number', models.CharField(blank=True, max_length=100)),
                ('plan_type', models.CharField(choices=[('hmo', 'HMO - Health Maintenance Organization'), ('ppo', 'PPO - Preferred Provider Organization'), ('epo', 'EPO - Exclusive Provider Organization'), ('pos', 'POS - Point of Service'), ('medicare', 'Medicare'), ('medicaid', 'Medicaid'), ('tricare', 'TRICARE'), ('other', 'Other')], max_length=20)),
                ('group_number', models.CharField(blank=True, max_length=100)),
                ('copay_primary_care', models.DecimalField(blank=True, decimal_places=2, help_text='Copay for primary care visits', max_digits=10, null=True)),
                ('copay_specialist', models.DecimalField(blank=True, decimal_places=2, help_text='Copay for specialist visits', max_digits=10, null=True)),
                ('copay_emergency', models.DecimalField(blank=True, decimal_places=2, help_text='Copay for emergency room visits', max_digits=10, null=True)),
                ('annual_deductible', models.DecimalField(blank=True, decimal_places=2, help_text='Annual deductible amount', max_digits=10, null=True)),
                ('out_of_pocket_max', models.DecimalField(blank=True, decimal_places=2, help_text='Annual out-of-pocket maximum', max_digits=10, null=True)),
                ('in_network_coverage', models.PositiveIntegerField(blank=True, help_text='Percentage covered for in-network providers (0-100)', null=True)),
                ('out_of_network_coverage', models.PositiveIntegerField(blank=True, help_text='Percentage covered for out-of-network providers (0-100)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('coverage_details', models.TextField(blank=True, help_text='Additional coverage details')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Insurance Plan',
                'verbose_name_plural': 'Insurance Plans',
                'ordering': ['provider__company_name', 'plan_name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('payer_id', models.CharField(blank=True, help_text='Insurance payer ID for claims', max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=17)),
                ('fax', models.CharField(blank=True, max_length=17)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('claims_address', models.TextField(blank=True, help_text='Address for claims submission')),
                ('electronic_claims_id', models.CharField(blank=True, help_text='ID for electronic claims submission', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_assignment', models.BooleanField(default=True, help_text='Whether provider accepts assignment')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Insurance Provider',
                'verbose_name_plural': 'Insurance Providers',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='1 = Primary, 2 = Secondary, etc.')),
                ('policy_holder_name', models.CharField(max_length=200)),
                ('policy_holder_relationship', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('other', 'Other')], default='self', max_length=20)),
                ('policy_holder_dob', models.DateField(help_text="Policy holder's date of birth")),
                ('policy_number', models.CharField(db_index=True, max_length=100)),
                ('group_number', models.CharField(blank=True, max_length=100)),
                ('member_id', models.CharField(blank=True, max_length=100)),
                ('effective_date', models.DateField(db_index=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_verified_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(blank=True, help_text='Status from last verification', max_length=50)),
                ('front_card_image', models.ImageField(blank=True, null=True, upload_to='insurance_cards/')),
                ('back_card_image', models.ImageField(blank=True, null=True, upload_to='insurance_cards/')),
                ('notes', models.TextField(blank=True)),
                ('insurance_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_coverages', to='insurance.insuranceplan')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_coverages', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Insurance',
                'verbose_name_plural': 'Patient Insurance Coverages',
                'ordering': ['patient', 'priority'],
            },
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='insurance.insuranceprovider'),
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(db_index=True, help_text='Unique claim number', max_length=100, unique=True)),
                ('service_date', models.DateField(db_index=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('diagnosis_codes', models.JSONField(default=list, help_text='List of ICD-10 diagnosis codes')),
                ('procedure_codes', models.JSONField(default=list, help_text='List of CPT/HCPCS procedure codes')),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount allowed by insurance', max_digits=10, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid by insurance', max_digits=10, null=True)),
                ('patient_responsibility', models.DecimalField(blank=True, decimal_places=2, help_text='Amount patient owes', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('appealed', 'Appealed'), ('denied', 'Denied')], db_index=True, default='draft', max_length=20)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('insurance_reference_number', models.CharField(blank=True, max_length=100)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('claim_form', models.FileField(blank=True, null=True, upload_to='insurance_claims/')),
                ('eob_document', models.FileField(blank=True, help_text='Explanation of Benefits document', null=True, upload_to='insurance_eob/')),
                ('notes', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claims', to='appointments.appointment')),
                ('patient_insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance.patientinsurance')),
            ],
            options={
                'verbose_name': 'Insurance Claim',
                'verbose_name_plural': 'Insurance Claims',
                'ordering': ['-service_date'],
            },
        ),
        migrations.AddIndex(
            model_name='patientinsurance',
            index=models.Index(fields=['patient', 'priority', 'is_active'], name='insurance_p_patient_32e099_idx'),
        ),
        migrations.AddIndex(
            model_name='patientinsurance',
            index=models.Index(fields=['policy_number'], name='insurance_p_policy__f548c9_idx'),
        ),
        migrations.AddIndex(
            model_name='patientinsurance',
            index=models.Index(fields=['effective_date', 'termination_date'], name='insurance_p_effecti_643b4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='patientinsurance',
            unique_together={('patient', 'priority')},
        ),
        migrations.AddIndex(
            model_name='insuranceplan',
            index=models.Index(fields=['provider', 'is_active'], name='insurance_i_provide_62d082_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='insuranceplan',
            unique_together={('provider', 'plan_name')},
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['patient_insurance', 'service_date'], name='insurance_i_patient_9d5cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['status', 'submission_date'], name='insurance_i_status_d23a63_idx'),
        ),
        migrations.AddIndex(
            model_name='insuranceclaim',
            index=models.Index(fields=['claim_number'], name='insurance_i_claim_n_de6fe8_idx'),
        ),
    ]
