# Generated by Django 4.2.7 on 2025-11-17 11:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_number', models.CharField(db_index=True, help_text='Unique order number', max_length=50, unique=True)),
                ('order_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('specimen_collected', 'Specimen Collected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=10)),
                ('clinical_indication', models.TextField(help_text='Clinical reason for ordering tests')),
                ('diagnosis_code', models.CharField(blank=True, help_text='ICD-10 code', max_length=50)),
                ('specimen_collected_at', models.DateTimeField(blank=True, null=True)),
                ('received_by_lab_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Lab Order',
                'verbose_name_plural': 'Lab Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_code', models.CharField(db_index=True, help_text='Standard test code (e.g., LOINC, CPT)', max_length=50, unique=True)),
                ('test_name', models.CharField(db_index=True, max_length=200)),
                ('test_category', models.CharField(choices=[('hematology', 'Hematology'), ('chemistry', 'Clinical Chemistry'), ('microbiology', 'Microbiology'), ('immunology', 'Immunology'), ('pathology', 'Pathology'), ('radiology', 'Radiology'), ('cardiology', 'Cardiology'), ('molecular', 'Molecular Diagnostics'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('specimen_type', models.CharField(blank=True, help_text='Type of specimen required (blood, urine, etc.)', max_length=100)),
                ('preparation_instructions', models.TextField(blank=True, help_text='Patient preparation instructions (e.g., fasting required)')),
                ('normal_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('normal_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Test price in USD', max_digits=10, null=True)),
                ('turnaround_time_hours', models.PositiveIntegerField(blank=True, help_text='Expected time to results in hours', null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lab Test',
                'verbose_name_plural': 'Lab Tests',
                'ordering': ['test_category', 'test_name'],
                'indexes': [models.Index(fields=['test_code'], name='laboratory__test_co_48df4e_idx'), models.Index(fields=['test_category', 'is_active'], name='laboratory__test_ca_b4c2f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('result_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('result_value', models.CharField(help_text='Test result value', max_length=500)),
                ('result_status', models.CharField(choices=[('pending', 'Pending'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('corrected', 'Corrected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('abnormal_flag', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('low', 'Low'), ('critical_high', 'Critical High'), ('critical_low', 'Critical Low'), ('abnormal', 'Abnormal')], db_index=True, default='normal', max_length=20)),
                ('interpretation', models.TextField(blank=True, help_text='Clinical interpretation of result')),
                ('reference_range', models.CharField(blank=True, help_text='Reference range applicable to this result', max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('performed_by', models.CharField(blank=True, help_text='Lab technician or analyzer', max_length=200)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.laborder')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='laboratory.labtest')),
            ],
            options={
                'verbose_name': 'Lab Result',
                'verbose_name_plural': 'Lab Results',
                'ordering': ['-result_date'],
            },
        ),
    ]
