# Generated by Django 4.2.7 on 2025-11-17 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_initial'),
        ('appointments', '0002_initial'),
        ('laboratory', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_lab_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborder',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lab_orders', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='specimen_collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specimen_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborder',
            name='tests',
            field=models.ManyToManyField(related_name='orders', to='laboratory.labtest'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['lab_order', 'lab_test'], name='laboratory__lab_ord_94e39b_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['result_status', 'result_date'], name='laboratory__result__ea597c_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['abnormal_flag'], name='laboratory__abnorma_35b7a3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='labresult',
            unique_together={('lab_order', 'lab_test')},
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient', 'order_date'], name='laboratory__patient_33ba48_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['doctor', 'order_date'], name='laboratory__doctor__b83657_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status', 'priority'], name='laboratory__status_94761c_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['order_number'], name='laboratory__order_n_0aa245_idx'),
        ),
    ]
